import type { AiSystem } from "@prisma/client";
import { parseJsonArray } from "./utils";

export function generateAnnexIvMarkdown(orgName: string, systems: AiSystem[]): string {
  const date = new Date().toISOString().slice(0, 10);
  const lines: string[] = [
    `# Annex IV Technical Documentation (Draft)`,
    ``,
    `**Organization:** ${orgName}`,
    `**Generated:** ${date}`,
    `**Status:** DRAFT — requires legal/compliance review before regulatory submission`,
    ``,
    `---`,
    ``,
    `## 1. General description of the AI system`,
    ``,
  ];

  if (systems.length === 0) {
    lines.push(`_No AI systems in inventory. Add systems before generating documentation._`);
    return lines.join("\n");
  }

  for (const [i, sys] of systems.entries()) {
    const dataTypes = parseJsonArray(sys.dataTypes);
    lines.push(
      `### 1.${i + 1} ${sys.name}`,
      ``,
      `| Field | Value |`,
      `|-------|-------|`,
      `| **Intended purpose** | ${sys.purpose} |`,
      `| **Description** | ${sys.description ?? "—"} |`,
      `| **Provider / Deployer role** | ${sys.roleType} |`,
      `| **Risk category (EU AI Act)** | ${sys.riskCategory} |`,
      `| **Annex III domain** | ${sys.annexIIIArea ?? "Not applicable / not assessed"} |`,
      `| **Vendor / model provider** | ${sys.vendor ?? "—"} |`,
      `| **Deployment environment** | ${sys.deploymentEnv ?? "—"} |`,
      `| **Personal data categories** | ${dataTypes.length ? dataTypes.join(", ") : "—"} |`,
      `| **Intended users** | ${sys.intendedUsers ?? "—"} |`,
      `| **Human oversight** | ${sys.humanOversight ?? "—"} |`,
      `| **Status** | ${sys.status} |`,
      ``,
      `#### Classification rationale`,
      ``,
      sys.classificationRationale?.trim()
        ? sys.classificationRationale
        : `_Not yet classified. Run risk classification in Registack AI._`,
      ``,
      `#### Development and design specifications`,
      ``,
      `- System source: ${sys.source}`,
      `- Last updated: ${sys.updatedAt.toISOString().slice(0, 10)}`,
      ``,
      `#### Monitoring, functioning, and control`,
      ``,
      `- Logging and oversight measures to be documented per deployer obligations (Art. 26) where applicable.`,
      `- Human-in-the-loop: ${sys.humanOversight ?? "Define oversight procedures."}`,
      ``,
      `---`,
      ``
    );
  }

  lines.push(
    `## 2. Detailed description of elements of the AI system`,
    ``,
    `_Expand with architecture diagrams, data flows, and model cards per system._`,
    ``,
    `## 3. Detailed information about monitoring, functioning and control`,
    ``,
    `_Document post-market monitoring plan if required for your risk class._`,
    ``,
    `## 4. Risk management system`,
    ``,
    `_Cross-reference risk register and mitigation measures._`,
    ``,
    `## 5. Changes to the system`,
    ``,
    `_Maintain version history; link to CI/CD change logs._`,
    ``,
    `---`,
    ``,
    `*Generated by Registack AI. This document is a draft and does not constitute legal advice.*`
  );

  return lines.join("\n");
}
